from setuptools import setup

setup(
    name='FairBPM',
    version='0.1',
    packages=['', 'venv.lib.python3.4.site-packages.py', 'venv.lib.python3.4.site-packages.py._io',
              'venv.lib.python3.4.site-packages.py._log', 'venv.lib.python3.4.site-packages.py._code',
              'venv.lib.python3.4.site-packages.py._path', 'venv.lib.python3.4.site-packages.py._process',
              'venv.lib.python3.4.site-packages.py._vendored_packages', 'venv.lib.python3.4.site-packages.pip',
              'venv.lib.python3.4.site-packages.pip._vendor', 'venv.lib.python3.4.site-packages.pip._vendor.idna',
              'venv.lib.python3.4.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.4.site-packages.pip._vendor.certifi',
              'venv.lib.python3.4.site-packages.pip._vendor.chardet',
              'venv.lib.python3.4.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.4.site-packages.pip._vendor.distlib',
              'venv.lib.python3.4.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.4.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.4.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.4.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.4.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.4.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.4.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.4.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.4.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.4.site-packages.pip._vendor.colorama',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.4.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.4.site-packages.pip._vendor.progress',
              'venv.lib.python3.4.site-packages.pip._vendor.requests',
              'venv.lib.python3.4.site-packages.pip._vendor.packaging',
              'venv.lib.python3.4.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.4.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.4.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.4.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.4.site-packages.pip._internal', 'venv.lib.python3.4.site-packages.pip._internal.req',
              'venv.lib.python3.4.site-packages.pip._internal.vcs',
              'venv.lib.python3.4.site-packages.pip._internal.utils',
              'venv.lib.python3.4.site-packages.pip._internal.models',
              'venv.lib.python3.4.site-packages.pip._internal.commands',
              'venv.lib.python3.4.site-packages.pip._internal.operations', 'venv.lib.python3.4.site-packages.ply',
              'venv.lib.python3.4.site-packages.attr', 'venv.lib.python3.4.site-packages.pluggy',
              'venv.lib.python3.4.site-packages._pytest', 'venv.lib.python3.4.site-packages._pytest.mark',
              'venv.lib.python3.4.site-packages._pytest._code', 'venv.lib.python3.4.site-packages._pytest.assertion',
              'venv.lib.python3.4.site-packages.betterast', 'venv.lib.python3.4.site-packages.dot_tools',
              'venv.lib.python3.4.site-packages.setuptools', 'venv.lib.python3.4.site-packages.setuptools.extern',
              'venv.lib.python3.4.site-packages.setuptools.command', 'venv.lib.python3.4.site-packages.pkg_resources',
              'venv.lib.python3.4.site-packages.pkg_resources.extern',
              'venv.lib.python3.4.site-packages.pkg_resources._vendor',
              'venv.lib.python3.4.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.4.site-packages.more_itertools',
              'venv.lib.python3.4.site-packages.more_itertools.tests', 'venv.lib64.python3.4.site-packages.pip',
              'venv.lib64.python3.4.site-packages.pip._vendor', 'venv.lib64.python3.4.site-packages.pip._vendor.idna',
              'venv.lib64.python3.4.site-packages.pip._vendor.pytoml',
              'venv.lib64.python3.4.site-packages.pip._vendor.certifi',
              'venv.lib64.python3.4.site-packages.pip._vendor.chardet',
              'venv.lib64.python3.4.site-packages.pip._vendor.chardet.cli',
              'venv.lib64.python3.4.site-packages.pip._vendor.distlib',
              'venv.lib64.python3.4.site-packages.pip._vendor.distlib._backport',
              'venv.lib64.python3.4.site-packages.pip._vendor.msgpack',
              'venv.lib64.python3.4.site-packages.pip._vendor.urllib3',
              'venv.lib64.python3.4.site-packages.pip._vendor.urllib3.util',
              'venv.lib64.python3.4.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib64.python3.4.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib64.python3.4.site-packages.pip._vendor.urllib3.packages',
              'venv.lib64.python3.4.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib64.python3.4.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.4.site-packages.pip._vendor.colorama',
              'venv.lib64.python3.4.site-packages.pip._vendor.html5lib',
              'venv.lib64.python3.4.site-packages.pip._vendor.html5lib._trie',
              'venv.lib64.python3.4.site-packages.pip._vendor.html5lib.filters',
              'venv.lib64.python3.4.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.4.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.4.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.4.site-packages.pip._vendor.lockfile',
              'venv.lib64.python3.4.site-packages.pip._vendor.progress',
              'venv.lib64.python3.4.site-packages.pip._vendor.requests',
              'venv.lib64.python3.4.site-packages.pip._vendor.packaging',
              'venv.lib64.python3.4.site-packages.pip._vendor.cachecontrol',
              'venv.lib64.python3.4.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.4.site-packages.pip._vendor.webencodings',
              'venv.lib64.python3.4.site-packages.pip._vendor.pkg_resources',
              'venv.lib64.python3.4.site-packages.pip._internal',
              'venv.lib64.python3.4.site-packages.pip._internal.req',
              'venv.lib64.python3.4.site-packages.pip._internal.vcs',
              'venv.lib64.python3.4.site-packages.pip._internal.utils',
              'venv.lib64.python3.4.site-packages.pip._internal.models',
              'venv.lib64.python3.4.site-packages.pip._internal.commands',
              'venv.lib64.python3.4.site-packages.pip._internal.operations', 'venv.lib64.python3.4.site-packages.ply',
              'venv.lib64.python3.4.site-packages.betterast', 'venv.lib64.python3.4.site-packages.dot_tools',
              'venv.lib64.python3.4.site-packages.setuptools', 'venv.lib64.python3.4.site-packages.setuptools.extern',
              'venv.lib64.python3.4.site-packages.setuptools.command',
              'venv.lib64.python3.4.site-packages.pkg_resources',
              'venv.lib64.python3.4.site-packages.pkg_resources.extern',
              'venv.lib64.python3.4.site-packages.pkg_resources._vendor',
              'venv.lib64.python3.4.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='jfair',
    author_email='',
    description=''
)
